### PR TITLE
Add image and twitter card support

### PR DESCRIPTION
**Pull request by DanielApt**
This makes shared links look pretty on FB and Twitter

### CODE REVIEW

**Comment by tjclement** [comment]
Awesome, thanks! I'm a bit of a jekyll noob: do I configure page.image in a page's front matter block?

**Comment by DanielApt** [comment]
Seems like it…

Local testing indicated your [PCB blog post](https://github.com/tjclement/pixel-badge-site/blob/main/blog/pcb_art.md) would already benefit from this feature.

Local dev server rendered the following inside the `<head>` tag:

```html
<title>A new tool in PCB design? How we made full colour PCB art - Pixel Badge ESP32 LED devboard</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="This post describes our initial ideas, the common pitfalls, and finally a working way of adding full colour PCB art to electronics projects."/>
        <link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i%26display=swap" rel="stylesheet"> 
        <link rel="stylesheet" href="/assets/css/main.css">
        
        
        <meta name="og:image" href="http://localhost:4000/images/pixel_badge_back.png"/>
        <meta name="twitter:card" content="summary_large_image" />
```

**Comment by tjclement** [comment]
Thanks a lot!

**Comment by DanielApt** [comment]
Hmmmm… in production it doesn't work.

Jekyll cannot construct an absolute URL (with the [`absolute`](,https://jekyllrb.com/docs/liquid/filters/) filter, because it does not know the site’s url.

Instead, it returns:
`<meta name="twitter:card" content="summary_large_image" />`

This will fail gracefully, so no urgency to fix.

**Path to fix**:
Make `site.url` available. I believe this is defined inside `_config.yml`

TBD: if the current PR can be re-opened, or if this will need to be a new PR…

**Comment by tjclement** [comment]
image

**Comment by DanielApt** [comment]
Fixed by https://github.com/tjclement/pixel-badge-site/commit/6fc84745a797d6abcedabd170449245b39aff042

**Comment by tjclement** [comment]
Was just about to comment here :) Thanks. It still uses a relative url instead of absolute for og:image, which is not what you'd expect when using `| absolute_url`. But it seems to work fine nonetheless!

**Pull request merged**
